- .gitignore
- README.md
- ausarbeitung.tcp
- ausarbeitung.tex
- bibliography.bib
- content/latex-tipps.tex
- preambel/packages_and_options.tex
All my changes wich helps to use the template
- Switching languages with only one comment change
- added usepackage subfig + example
- Including DOI's for better handling of the references
- fix wrong heading for List of Acronyms in the English version
- no use of abbreviations when using \cref{} to use abbreviations here is not common the a thesis
- standard use of \usepackage{acro} for abbreviations + example
-  second table example for nice number formatting
> Easier template handling

- ausarbeitung.tex
This change overrides the compile command to use `make` for some common IDEs (such as TeXStudio).
> Choose make as compiler (instead of the default)

- CHANGELOG.md
- preambel/packages_and_options.tex
- Since the last release non-inline todos were broken. I fixed this in a427b46. The todo package has to be loaded after geometry (see http://ftp.math.purdue.edu/mirrors/ctan.org/macros/latex/contrib/todonotes/todonotes.pdf)
- The name of the 'List of Todos' depends now on the thesis language
- Also colors are displayed in the 'List of Todos'
Regards
> Fix non-inline todos and tweaks to todo package

- CHANGELOG.md
- preambel/packages_and_options.tex
Translate the float name of the "Algorithmus" environment if english is selected as language (fixes #60) and translate the float name of the "algorithm" environment only if german is selected as language.
> Fix translation of float name of "Algorithmus" and "algorithm" environment

- config.tex
This enables line breaks in long urls which are not separated by spaces or slashes
Prevens that the URLs run in the margin
https://tex.stackexchange.com/a/134281
<...describe the change...>
> Update biblatex options to break long lines

- config.tex
- docs/adr/0003-use-minted-for-code-highlithing.md
Fixed minor misspelling in adr 0003 resulting in incorrect link rendering for pygmentex.
Fixed incorrect ctan-linkage of listings to minted.
Also adds a bit of documentation on the usepackage for csquotes referring to the results of investigations into fvextra complaining about it.
> Minor general fies to get acquainted with the repository

- config.tex
In the german version of the template captions are wrongly translated. For example "Contents" instead of "Inhaltsverzeichnis" and so on.
Babel gave the following warning:
```
Package babel Warning: Last declared language option is `ngerman',
(babel)                but the last processed one was `american'.
(babel)                The main language cannot be set as both a global
(babel)                and a package option. Use `main=ngerman' as
(babel)                option. Reported on input line 460.
```
Using `main=ngerman' fixes the problem.
(I am not sure if this small fix is changelog worthy)
> Fix wrongly translated captions

- config.tex
Fix #110
The Fontspec command `\setmainfont` explicitly sets fonts for italic, bold and bold italic.
> Fix italics and bold in body text

- CHANGELOG.md
- config.tex
Change fontenc newtxmath solution from https://tex.stackexchange.com/a/394139/9075 to the second proposed fix of https://tex.stackexchange.com/a/394137.
> Fix font in math environment `\mathrm`

- CHANGELOG.md
- config.tex
> Fix renaming of `\acronymname` when using german

- CHANGELOG.md
- config.tex
Fixes latextemplates#123 by adding the other variants to the definition
> For Lua(La)TeX, define missing sans font variants

- docs/README.md
koopor/texlive is not maintained anymore. danteev/texlive is the maintained version
> Fix link to docker image

- CHANGELOG.md
- docs/README.md
This PR repairs the PlantUML setup link in the docs.
> Replace plantuml setup link with a working link

- config.tex
This is a fix for #139.
The _siunitx_ package seems to have deprecated the `group-four-digits` option. There is compatibility code, however that only works if the option is explicitly set by `group-four-digits=true`. Thus, the compilation breaks as described in #139. As the option is mapped to `group-minimum-digits=4` internally, I would use that option in _config.tex_.
> Fix deprecated siunitx option in config

- CHANGELOG.md
- config.tex
Cleanup the math and font config stuff. I tested it on a recent texlive distribution.
This note is not really relevant (already long outdated; my `git blame` search was based on a pretty old version)
~This PR seems to different than dcfec4af3c87e911746b8d9d1818cbbf2a2bbd61 though, which claimed to fix the font config for MikTex. (Did not test MikTex)~
I did not test it with MiKTeX, though.
> Cleanup math and font stuff

- docs/README.md
Thanks for the great template :)
I had to update the docker commands to get it running on my computer (Ubuntu 22.04) and I thought I would contribute the changes
The issue is that the previous docker commands mount the contents to `/home` and assumes that all relative paths will also start from home. If this worked in the past, I guess it's because `/home` used to be the default working directory of the `danteev/texlive` docker image. 
**However, this is no longer the case**, if you run the image the default working directory is `/workdir`.
The simplest fix would be to just mount to `/workdir` instead of `/home`, however this would start failing if the default working directory changed in the future.
I tested it and it worked, but the extremely useful Right-click "Go To Source" and "Go To …
> Fixed docker compilation commands & sync

- docs/README.md
docs: Add instructions for using VSCode with LaTeX Workshop
- Added instructions for using VSCode to edit, compile, and preview PDFs with LaTeX Workshop.
- Mentioned that the configuration from the provided guide might need modifications for this template.
- Included prerequisites for installing VSCode, LaTeX Workshop, and a LaTeX distribution (e.g., MiKTeX or TeX Live).
- Provided a JSON configuration snippet to add to `settings.json` for recommended VSCode setup.
Closes #149
> docs: Add instructions for using VSCode with LaTeX Workshop

- main-english.tex
- main-german.tex
Students must submit a German abstract in addition to the English abstract in most of the courses. So, it makes sense to add both abstracts to the template to make this less confusing and uniform for all submissions.
> Add German Abstract to English Version

- config.tex
The title of the list of abbreviations should be "List of Abbreviations" but shows "Acronyms." To fix this, we add \acronymname to \addto\captionsenglish.
> Fix \acronymname in English Version

- .github/workflows/build-and-publish-with-latexmk.yml
- CHANGELOG.md
- README.md
- Fix display name of latexmk action
- Fix mention of license in README (already changes some while back)
- Add quick summary of allowed relicensing
> Fix typo and license hint
